dist: bionic

language: python

python:
    - "3.8.5"
  
install:
    - pip install -r requirements.txt
    - python setup.py install

jobs:
    include:
        - stage: test
          name: "Tests"
          script:
              - cd tests
              - python -m unittest